wecode-bootcamp-korea/justcode-4-2nd-carrot-country-front

.eslintrc
.prettierrc

[임근홍]add: eslint, prettier 추가

---

src/App.js
src/components/modal/Modal.js
src/components/signup/Signup.js
src/components/signup/SignupStyle.js
src/components/slider/ImageSlider.js
src/nav/Header.js
src/pages/main/MainStyle.js

FIX: 헤더 컴포넌트에 회원가입 연결

---

src/nav/HeaderStyled.js

<br />
- 헤더 고정
<br />
헤더 고정
<br />
헤더 고정!
<br />
- 메인페이지 살짝 내랴야할거같아요 윈도우 사이즈가 작아지면 겹칩니당

[add] header fixed

---

src/components/slider/ImageSlider.js

FIX: 이미지 슬라이더 스타일 변경

---

src/App.js
src/blocker.js
src/components/buttons/LeavePageButton.js
src/components/buttons/RegisterButton.js
src/components/buttons/SubmitButton.js
src/components/list/DistrictInfoCard.js
src/nav/HeaderStyled.js
src/pages/districtInfo/DistrictInfo.js
src/pages/districtInfo/DistrictInfoRegister.js
src/pages/districtInfo/DistrictInfoRegisterStyled.js
src/pages/districtInfo/Editor.js
src/pages/product/ProductRegister.js

<br />
- register 구현
<br />
1. router 추가
- 애니메이션 되어있는 동그란 버튼 누르면 각 등록 페이지로 넘어갑니다.
2. 동네정보 register page 
- UI를 좀 변경했습니다.
- api랑 연결하진 못했습니다. 
3. blocker.js : register page 뒤로가기, 새로고침 blocker 
- 글이 저장안되기때문에 중간에 나가거나, 새로고침하거나, 뒤로갈 경우 alert 뜨게함
+)
register page 전부 들어가면 페이지 가장 상단으로 가도록 해뒀습니다.
<br />
- react hook, react router dom 에 대해서 공부했습니다.
<br />
- api 연결만 잘 해결되면 좋겟습니다.....

[임근홍] add: register router 추가, 동네정보 register page 추가,  register page 뒤로가기, 새로고침 blocker 

---

src/pages/product/Editor.js
src/pages/product/ProductImageModal.js
src/pages/product/ProductRegister.js

<br />
- 매물 등록 기능 구현
<br />
1. 사진 미입력시 등록 불가
2. 제목 1글자 미만시 등록 불가
3. 내용 5글자 미만시 등록 불가
<br />
- useState의 사이클에 대해 다시 한번 생각해보게 되었습니다.
<br />
- 현재 api 연결이 하나도 안된 상태로 월요일에 연결할 예정
- 고로 등록 버튼 눌러도 등록이 되는 상태는 아님

FIX: 상품 등록 페이지 구현

---

src/apis/area.js
src/apis/chat.js
src/apis/user.js
src/components/chat/ChatList.js
src/components/chat/ChatRoom.js
src/components/chat/ChatRoomFooter.js
src/components/modal/ImageModal.js
src/components/signup/Signup.js
src/components/slider/ImageSlider.js
src/pages/chat/Chat.js
src/pages/product/ProductDetail.js

ADD: 로그인, 카테고리, 지역 apis 추가

---

src/pages/product/ProductDetail.js

<br />
- 매물 조회수 기능
<br />
1. 매물 조회 카운터 생성
<br />

ADD: 매물 조회 카운터

---

src/components/buttons/DistrictSelectDropDown.js
src/components/list/ProductInfoList.js
src/components/list/ProductInfoListCard.js
src/pages/product/ProducInfo.js

<br />
-인기 매물 리스트 
<br />
1. 현재 드롭다운 일체 추가 상태, 근홍님 그거 빼시고 위치 넣어서 작업하시면 됩니다!
<br />
<br />

FIX: 기본 동네정보 리스트 작성용 

---

src/apis/category.js
src/components/buttons/DistrictSelectDropDown.js
src/components/list/ProductInfoList.js
src/pages/product/ProducInfo.js

<br />
- 지역  불러와서 선택해서 저장하는거  구현 완료
<br />
1. 지역  불러와서 선택해서 저장하는거  구현 완료
<br />
<br />
- 지역 선택에 따라 지역 리스트 불러오는거 구현 해야함

FIX: 인기매물 리스트 구역 선택 구현

---

src/apis/product.js
src/pages/product/Editor.js
src/pages/product/ProductRegister.js

<br />
- 매물 등록 API 연결중
<br />
1. API 작성 하였고 로그인 후 등록 되나 확인해야함
<br />
<br />

ADD: 매물 등록 페이지 AP I연결 추가

---

src/apis/district.js
src/apis/product.js
src/components/chat/ChatRoom.js
src/components/chat/ChatRoomContent.js
src/components/chat/ChatRoomFooter.js
src/components/list/ProductInfoList.js
src/components/list/ProductInfoListCard.js
src/pages/chat/Chat.js
src/pages/districtInfo/DistrictInfo.js
src/pages/product/ProducInfo.js
src/pages/product/ProductDetail.js

<br />
-매물 list 연결했습니당
<br />
-매물 list 연결했습니당
<br />
-예외처리...
<br />

[임근홍] add: 매물 list 연결 완료

---

src/apis/product.js
src/context/context.js
src/pages/main/Main.js
src/pages/product/ProductDetail.js
src/pages/product/ProductDetailStyle.js

FIX: 컨텍스트 버그 수정/ 매물 좋아요 기능

---

src/components/login/Login.js
src/pages/product/ProductDetail.js
src/utils/format.js
src/utils/format.spec.js
src/utils/unitTest.spec.js

<br />
- 자연스러운 로그인 반응
<br />
- 로그인 성공 후 alert이 제거되며 자연스러운 fade out으로 변경됬습니다.
<br />
<br />

FIX: 로그인 성공 반응 수정

---

src/apis/district.js
src/components/chat/ChatRoom.js
src/components/chat/ChatRoomContent.js
src/components/chat/ChatRoomContentStyled.js
src/components/chat/ChatRoomFooter.js
src/components/list/DistrictInfoCard.js
src/components/list/ProductInfoList.js
src/components/list/ProductInfoListCard.js
src/pages/chat/Chat.js
src/pages/districtInfo/DistrictInfo.js
src/pages/product/ProducInfo.js

<br />
- 채팅 구분 & 동네정보 api연결
<br />
채팅 구분 & 동네정보 api연결
<br />
<br />

[임근홍]add: 채팅 구분 & 동네정보 api연결

---

src/pages/districtInfo/DistrictInfo.js

<br />
- 동네소식 없을때 없다는 페이지뜨도록 변경
<br />
동네소식 없을때 없다는 페이지뜨도록 변경
<br />
- 렌더링
<br />

임근홍 [fix] 동네소식 없을때 없다는 페이지뜨도록 변경

---

src/components/chat/ChatRoom.js
src/pages/chat/Chat.js

ADD: 챗룸 매물정보 받아오기

---

src/apis/product.js
src/components/list/ProductInfoListCard.js
src/pages/product/Editor.js
src/pages/product/ProductRegister.js

<br />
<br />
1. 삭제 버튼 짤리는 스타일 수정
2. 매물 등록 기능 구현 완료...
<br />
- 데이터를 저장하고 운용하고 전송하는 부분에 관여하는 모든 부분에 대해 배웠고 formData에 대해 배웠습니다.
<br />
-드디어... 완료....

FIX: 매물 등록 기능 구현 완료, 매물 사진 삭제 버튼 수정

---

src/apis/product.js
src/components/buttons/RegisterButton.js
src/components/chat/ChatList.js
src/components/chat/ChatRoom.js
src/components/chat/ChatRoomContent.js
src/components/chat/ChatRoomContentStyled.js
src/components/chat/ChatRoomFooter.js
src/components/list/AreaTag.js
src/components/list/ProductInfoListCard.js
src/pages/chat/Chat.js
src/pages/districtInfo/DistrictInfoRegister.js
src/pages/districtInfo/DistrictInfoRegisterStyled.js
src/pages/districtInfo/Editor.js
src/pages/product/Editor.js
src/pages/product/ProductDetail.js
src/pages/product/ProductRegister.js

임근홍: [fix] 수정

---

src/components/chat/ChatRoomContentStyled.js
src/pages/districtInfo/DistrictInfo.js

임근홍: [fix] chatRoomContent styled 변경 & 동네소식예외오타수정

---

src/components/loading/Loading.js
src/pages/districtInfo/DistrictInfo.js
src/pages/product/ProducInfo.js

[add] loading 컴포넌트

---

src/apis/district.js
src/pages/districtInfo/DistrictInfoRegister.js
src/pages/districtInfo/Editor.js
src/pages/product/Editor.js
src/pages/product/ProductRegister.js

<br />
[add] 동네소식 올리기 구현 완료 & [fix] 불필요한 폴더 삭제
<br />
[add] 동네소식 올리기 구현 완료 & [fix] 불필요한 폴더 삭제
<br />
[add] 동네소식 올리기 구현 완료 & [fix] 불필요한 폴더 삭제
<br />

[add] 동네소식 올리기 구현 완료 & [fix] 불필요한 폴더 삭제

---

src/apis/comment.js
src/components/comment/CommentInput.js
src/pages/districtInfo/DistrictInfoDetail.js

댓글 등록 작업 구현중

---

src/pages/search/SearchMain.js

<br />
- 검색어에 따라 다른 데이터 불러와서 뿌려주기
<br />
1. 현재는 인기매물 리스트 불러와 놓은 상태
<br />
<br />
- 기능 아직 아무것도 추가 안됨

ADD: 검색페이지 레이아웃 구현

---

src/components/chat/ChatList.js
src/components/chat/ChatListStyle.js
src/components/list/GridList.js
src/components/login/Login.js
src/components/login/LoginStyle.js
src/nav/Header.js
src/pages/chat/Chat.js
src/pages/districtInfo/DistrictInfo.js
src/pages/districtInfo/DistrictInfoDetail.js
src/pages/districtInfo/DistrictInfoDetailStyled.js
src/pages/product/ProductDetail.js
src/pages/product/ProductDetailStyle.js
src/utils/format.js
src/utils/format.spec.js

ADD: timeFormat (date type 넣을 시 00시간전 등 으로 반환)

---

src/apis/district.js
src/apis/product.js
src/nav/Header.js
src/pages/search/SearchMain.js

<br />
<br />
1. 검색어 입력 후 검색할 시 검색 결과 보여주기
2. 헤더 돋보기 아이콘 클릭시 검색 실행
<br />
- 필터링에 대해 조금 더 알게 되었습니다
<br />
- 현재 리스트 컴포넌트의 렌더링 길이에 제한이 있고 더보기에 기능이 없는 상태, 리팩토링 할 때 숫자 제한한 무한 스크롤 구현 예정

FIX: Search 페이지 API 연결, 헤더 아이콘 클릭시 검색 

---

src/components/list/DistrictInfoCard.js
src/nav/Header.js

[fix] 스크롤 고정

---

src/pages/chat/Chat.js

임근홍 [add] chat List 애니메이션추가

---

src/apis/comment.js
src/components/comment/CommentInput.js
src/pages/districtInfo/DistrictInfoDetail.js

Feature/district info/detail

---

src/apis/product.js
src/pages/search/SearchMain.js

검색 페이지 minor fix

---

src/App.js
src/components/list/ProductInfoList.js
src/components/scrollToTop/ScrollToTop.js
src/nav/Header.js
src/pages/product/ProducInfo.js

<br />
[add] scrollToTop & [fix] 불필요한 요소 삭제
<br />
[add] scrollToTop & [fix] 불필요한 요소 삭제
<br />
- window.history에 대해 알게 됨
<br />

[add] scrollToTop & [fix] 불필요한 요소 삭제

---

src/apis/product.js
src/pages/product/Editor.js
src/pages/product/ProducInfo.js
src/pages/product/ProductRegister.js

<br />
- 매물 등록 페이지 반응형 구현
<br />
1. 모바일 너비에서 적용되지 않았던 반응형 수정 완료
<br />
- 추후에 다른 요소들도 추가적으로 수정할 예정입니다

FIX: 매물 등록 페이지 레이아웃 반응형으로 수정 완료

---

src/components/chat/ChatListStyle.js
src/components/chat/ChatRoomContentStyled.js
src/nav/Header.js
src/nav/HeaderStyled.js

<br />
- 당근채팅 새로운 메세지가 왔을 때 헤더 당근채팅 버튼에 뱃지가 생성됩니다.

ADD: 헤더 당근채팅버튼 알림 기능

---

src/components/buttons/LeavePageButton.js
src/components/buttons/RegisterButton.js
src/components/chat/ChatRoomContent.js
src/pages/districtInfo/DistrictInfoDetail.js
src/pages/districtInfo/DistrictInfoRegister.js
src/pages/districtInfo/Editor.js
src/pages/product/Editor.js
src/pages/product/ProductRegister.js

<br />
- 멘토님 피드백 받은부분 
클릭 이벤트로 goTodetail 옮겼습니당
<br />
1. 더 간단해진 
<br />
- 함수정리
<br />

[fix] navigate 함수 위치 변경, 반복함수 합치기

---

src/apis/comment.js
src/components/comment/CommentInput.js
src/pages/districtInfo/DistrictInfoDetail.js

댓글 등록 삭제 완료

---

src/components/buttons/DetailDeleteModal.js
src/pages/product/Editor.js
src/pages/product/ProductDetail.js
src/pages/product/ProductDetailStyle.js
src/pages/product/ProductEdit.js

ADD: 매물 삭제 기능 추가

---

src/apis/product.js

FIX: 누락 함수 추가

---

src/App.js
src/apis/product.js
src/components/buttons/DetailDeleteModal.js
src/pages/product/EditEditor.js
src/pages/product/ProductDetail.js
src/pages/product/ProductEdit.js

ADD: 수정 기능 추가

---

src/components/buttons/DistrictSelectDropDown.js

FIX: 비로그인 매물리스트 hotfix

---

src/components/buttons/DetailDeleteModal.js

[add] district delete 포함

---

src/components/buttons/DetailDeleteModal.js

[add] district delete 수정

---

src/components/chat/ChatList.js
src/components/chat/ChatListStyle.js
src/pages/chat/Chat.js
src/pages/districtInfo/DistrictInfo.js
src/pages/product/ProducInfo.js

[fix] district rendering & [fix] 매물없는 동네 동네매물페이지 오류

---

src/pages/product/ProducInfo.js
src/pages/product/ProductDetail.js
src/pages/product/ProductDetailStyle.js

FIX: 수정버튼 주석, 삭제 버튼 css 조정
